// Filesystem layout for companion-owned session/artifact data.
//
// Follows the existing convention already used by host/native-host.js for
// recordings/audits/screenshots: everything lives under
// ~/.config/browzy-in-chrome/<subdir>/, one directory per user, so a
// companion running as a different OS user never collides with another's
// data. Kept private (no group/world access) the same way endpoint.js scopes
// the bridge socket to the current user.
//
// OCIC_AGENT_HOME overrides the root — tests use this to point every path at
// a scratch directory instead of the real per-user config directory.

import fs from "node:fs";
import os from "node:os";
import path from "node:path";

export function agentRoot() {
  if (process.env.OCIC_AGENT_HOME) return process.env.OCIC_AGENT_HOME;
  return path.join(os.homedir(), ".config", "browzy-in-chrome", "agent");
}

export function conversationsDir() {
  return path.join(agentRoot(), "conversations");
}

export function conversationDir(conversationId) {
  assertSafeId(conversationId, "conversationId");
  return path.join(conversationsDir(), conversationId);
}

export function conversationArtifactsDir(conversationId) {
  return path.join(conversationDir(conversationId), "artifacts");
}

// User-composer attachments (pasted/dropped/picked images) live in their own
// subdirectory under the conversation's artifacts dir, deliberately distinct
// from the top-level dir the action-timeline screenshot artifacts occupy:
// same private, per-conversation, user-owned tree (and the same
// deleteConversation() cleanup), but the two byte populations never share a
// path, so a screenshot-retention/export rule can never sweep up a user
// attachment — or the reverse — by accident.
export function conversationAttachmentsDir(conversationId) {
  return path.join(conversationArtifactsDir(conversationId), "attachments");
}

// Agent-created documents (the `create_document` tool's output) live in their
// own subdirectory of the conversation, deliberately outside `artifacts/`:
// artifacts hold bytes the BROWSER produced (screenshots) or the OPERATOR
// uploaded (composer attachments), while these are files the RUN produced for
// the operator to read and download. Keeping the two populations on separate
// paths means a retention or export rule written for one can never sweep up
// the other. Same per-conversation privacy and same deleteConversation()
// cleanup as every other conversation-owned directory.
export function conversationDocumentsDir(conversationId) {
  return path.join(conversationDir(conversationId), "documents");
}

export function conversationEventsFile(conversationId) {
  return path.join(conversationDir(conversationId), "events.jsonl");
}

export function conversationMetaFile(conversationId) {
  return path.join(conversationDir(conversationId), "meta.json");
}

// Conversation/run/artifact identifiers are generated by this codebase only
// (never taken verbatim from page content or a model), but validate anyway:
// this id becomes a path segment, and a stray "../" here would be a
// traversal bug baked into every caller that trusts it.
export function assertSafeId(id, label = "id") {
  if (typeof id !== "string" || !/^[A-Za-z0-9_.-]{1,128}$/.test(id)) {
    throw new Error(`invalid ${label}: ${JSON.stringify(id)}`);
  }
  if (id === "." || id === "..") throw new Error(`invalid ${label}: ${id}`);
  return id;
}

export function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
  if (process.platform !== "win32") {
    try {
      fs.chmodSync(dir, 0o700);
    } catch {}
  }
  return dir;
}
